# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'rnToday_2' do

#pod 'SSZipArchive', '~> 1.1'

end

target 'rnToday_2Tests' do

end

